apiVersion: v1
kind: Service
metadata:
  name: bank-sys-svc
  namespace: bank-app
spec:
  selector:
    app: bank
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
      nodePort: 32595
  type: NodePort

